### ISSUE TITLE
Category view HTML

### ISSUE THREAD

**Issue by daduon** [pnc-virtual-company/2020-G9-letsgo#13]
A view composed of
- HTML AND CSS

**Comment by vannuthchhorn** [comment]
@ronann could you review my task and now I completed my task.

**Comment by ronanpnc** [comment]
I'm not aggree on this commit

category route should be routed to a AdminControler  not a UserControler

- AdminControler manages the admin operations
- userControler manage the user profile and sign int / out

**Comment by vannuthchhorn** [comment]
Teacher, so I need to create a new file for AdminControler or not?

**Comment by vannuthchhorn** [comment]
@ronann update routes file and Usercontroler to Admincontroler.
