### ISSUE TITLE
Add Logout feature   (HTML/CONTROLER/SESSION..)

### ISSUE THREAD

**Issue by daduon** [pnc-virtual-company/2020-G9-letsgo#16]
Click on LOG OUT menu item

It shall disconnect the current user from the application

- Logout fuction : using the destroy session to back to login .
- navbar file : include the session get to catch only first name display in menu and then when we click on logout it will back to login form

**Comment by sreyneang040** [comment]
@ronanpnc Please project manager help to review my task  already completed.

**Comment by ronanpnc** [comment]
No in this task you are support to perfrom the code to log out

Not just only the view

PLease read the specifications of the tasks

**Comment by sreyneang040** [comment]
@ronanpnc Please teacher help to review my task related to logout process. Because I have already completed.
