### ISSUE TITLE
Add Login feature

### ISSUE THREAD

**Issue by Puthy-Ouk** [pnc-virtual-company/2020-G9-letsgo#17]
Login to the application.

>>> then ?  are you using a session ? can you explain tehcnically what you will do ?

- UserRole : in this class have function validateUser it will return true if email and password  match with account in database. 
- UserController : Write the procces of login include with validate of error.
Login file : form of login .

**Comment by sreyneang040** [comment]
@ronanpnc I would like to inform project manager help to review my task related to login process. I have already completed.

**Comment by ronanpnc** [comment]
1 - Master Master to your branch

2- Fix bad coede  in  UserRole  :  comment + deadcode +

**Comment by sreyneang040** [comment]
@ronanpnc I would like to inform teacher I confused push login process to master branch. Because I forgot check out my branch. So I really sorry teacher for my mistake.
