### ISSUE TITLE
Manage categories

### ISSUE THREAD

**Issue by Puthy-Ouk** [pnc-virtual-company/2020-G9-letsgo#19]
+The view shall allow a user to:
 - Filter category by name
 - Create a new category (main action)
 - Edit /remove a category (secondary actions, when the mouse is on hover)
+This view is accessible only by ADMIN.

**Comment by ronanpnc** [comment]
1- Spearete the JS code from HTML and CSS

2 Bug : When i edit again the category, a error is diplsyaed "Name already exist" even if i type a different name

**Comment by Puthy-Ouk** [comment]
@Sethmok @ronanpnc 
  Dear teacher,

     I write the message to inform the teacher about the future that my team change on the message when data had already on the database. The message success and error it displays after clink on the button create and update because it difficult to do it so, my team finds the other way to do it if had time to do it I will change it later and this point I ask permission from Ronan already and Ronan agree with it.

Best regards,

Puthy Ouk
![ceateSuccess](https://user-images.githubusercontent.com/54493889/88692523-5c8f1780-d128-11ea-85c6-caf80d8454b2.PNG)
![error](https://user-images.githubusercontent.com/54493889/88692559-657fe900-d128-11ea-8149-42e5aec75a7d.PNG)
![updateaSuccess](https://user-images.githubusercontent.com/54493889/88692571-6c0e6080-d128-11ea-8cc2-bc4aa944ad77.PNG)
