### ISSUE TITLE
All database tables 

### ISSUE THREAD

**Issue by daduon** [pnc-virtual-company/2020-G9-letsgo#2]
The database shall be composed of the following items:
- tables

**Comment by daduon** [comment]
@ronanpnc I would like to project manager check verify database table of my group.

**Comment by ronanpnc** [comment]
@daduon ok I am reviewing it

**Comment by ronanpnc** [comment]
REVIEW => TO BE IMPROVED

Event
	missing the information of the uploaded image

	start/end date => bad type
	description		=> 45 character might not be enougth, ask the customer 
			   how many characer max for the desription


	User_user : name not clear

Join
	don't dont need the event categor : it's already in Event


User
	missing the information of the uploaded image

**Comment by ronanpnc** [comment]
Naming conventions are not correct (camel case)

Join table name is not clear

**Comment by daduon** [comment]
Yes teacher I will change it. Thank you teacher.
