### ISSUE TITLE
Read  JSON cities

### ISSUE THREAD

**Issue by Puthy-Ouk** [pnc-virtual-company/2020-G9-letsgo#20]
+ The list of cities available in the application shall be retrieved from a JSON
+ The JSON file shall contain for each city the following information:
  - City name
   - City country
+ This file shall be read-only once and stored into memory.
+ This list of cities will be then used to select a city in the different combo boxes of the application

**Comment by daduon** [comment]
@ronanpnc  Good morning teacher. I would like to inform the teacher to check my task.

**Comment by ronanpnc** [comment]
BUG 1 -----------------------------------------------------
JSON file should be on server, not on the web

   $serverJson = file_get_contents('https://run.mocky.io/v3/7ea62752-cb4e-4d5a-94cf-1e37e9442e9f');
      
-> NO

Put the JSON file on / public/something/

BUG2 ----------------------------------------------------

We want the list of cities , not countries

You should display all cities and display their country in parenthis

**Comment by daduon** [comment]
@ronanpnc Teacher I not clear about Json on server and Json on web. teacher can explain or example for me. And not clear about display all cities and display their country in parenthis. teacher can example for me.

**Comment by ronanpnc** [comment]
@daduon  OK
