### ISSUE TITLE
Edit profile 

### ISSUE THREAD

**Issue by Puthy-Ouk** [pnc-virtual-company/2020-G9-letsgo#21]
+ A popup is displayed, allowing the user to edit his/her profile:
   o First name, last name
   o Mail (must be a valid mail address)
   o Password
       upload / delete image
        Gender 
        city
        date of birthday

**Comment by vannuthchhorn** [comment]
@ronann I want to ask you specifics about User profile pop up your requirement is not clear I want you to detail about it.

**Comment by sreylengchheang** [comment]
Hello teacher I don't know how to upload/edit and remove image profile. And I need to create new function or I use the same function updateProfile?

**Comment by sreylengchheang** [comment]
@ronanpnc 
Hello teacher I would like you to help about delete image.

**Comment by ronanpnc** [comment]
@sreylengchheang 
Does not work

1 - Create a new account

2 Update profile

3 - Change first name

4 click on UPDATe

=> a whoopps page is displayed

**Comment by sreylengchheang** [comment]
@ronanpnc 
Why create a new account does not work ???? 
Puthy clone from master and she test it work

**Comment by sreylengchheang** [comment]
@ronanpnc 
teacher for update profile if user don't want to update information and user click on update, so what happen ????

**Comment by sreylengchheang** [comment]
@ronanpnc 
hello teacher I would like to ask teacher about update profile. if user click on update button but user not change information so how to compare between old data and new data????

**Comment by ronanpnc** [comment]
old data is in your database

new data : you get it from the POST requet after clicking on SUBMIT


Ronan OGOR, WEP Coordinator

Passerelles numériques CAMBODIA

BP511 St. 371 Phum Tropeang Chhuk (Borey Sorla), Sangkat Tek Thla, Khan Sen
Sok, Phnom Penh, CAMBODIA

Email@passerellesnumeriques.org | Phone: + 855 23 99 55 00 | Mobile: +855
96 49 02 951 | Skype ID: ronan.ogor

<https://www.passerellesnumeriques.org/en/about-us/our-organisation/>

<http://www.passerellesnumeriques.org/>
<https://www.facebook.com/passerelles.numeriques>
<https://www.linkedin.com/company/455759/>
<https://twitter.com/passerellesNume>
<http://www.youtube.com/user/PasserellesNumerique>

**Comment by sreylengchheang** [comment]
@ronanpnc 
yes teacher I understand it but don't know how compare between old data and new data when we click on update.
-one more thing I difficult to do delete only profile picture in database.

**Comment by ronanpnc** [comment]
Git ignore image which are uploaded by user

Put them in a specific folder and ignore this folder

**Comment by sreylengchheang** [comment]
@ronanpnc 
Hello teacher for edit profile I think I spend much time to do and my team help me to fix to but we still not complete and very difficult me and members in team discuss about this problem we think we can skip or stop this task because we don't want to loss time to do it.  If we have time we will back to do it.

**Comment by sreylengchheang** [comment]
@ronanpnc 
Hello teacher for #21 I completed and **missing delete imag**e that I skip.
![editeprofile](https://user-images.githubusercontent.com/53991715/88754432-d7881a80-d188-11ea-860c-0a3e2d4a0ede.PNG)
But for delete only image I skip because don't want to spend much time to complete. if I try to complete it I lose time.
