### ISSUE TITLE
Add date of birth, gender and city to edit profile

### ISSUE THREAD

**Issue by Puthy-Ouk** [pnc-virtual-company/2020-G9-letsgo#25]
+ Add date of births, gender and city to edit profile on file view, database, and model

**Comment by ronanpnc** [comment]
Change the TAG : it's an IMPROVEMENT

CHange the title : what are the fields to be added ? Your title shoud be clear enought

**Comment by ronanpnc** [comment]
@Puthy-Ouk 
Please review this issue - see my comments

**Comment by ronanpnc** [comment]
i cannot see any commit regarding this issue..
