### ISSUE TITLE
It should not be possible to access to views from URL if not connected

### ISSUE THREAD

**Issue by ronanpnc** [pnc-virtual-company/2020-G9-letsgo#31]
When typing the following URLs :
<base_ulr>/profile
<base_ulr>/explore
<base_ulr>/yourEvents
<base_ulr>/explore
<base_ulr>/category

If no user connected to the application, a error message should be displayed

**Comment by daduon** [comment]
@ronanpnc Good morning teacher. I would like to inform the teacher to check my task.
