### ISSUE TITLE
Create event pop up

### ISSUE THREAD

**Issue by vannuthchhorn** [pnc-virtual-company/2020-G9-letsgo#35]
- Create an event pop up:
   .   when clicking on the button it shows the form for 
       input information
    .  on-field event category can select name event
    .  input Title
    .  The end date shall be AFTER the start date (or 
       same day)
     . At field are related to a time (e.g. : 2.00 PM 
       or 08.30 AM )
     .  select city
     .  input description
-  Profile image:
1. Upload image
2. Edit Image
3. Remove image

**Comment by vannuthchhorn** [comment]
@ronanpnc 
Hello, teacher, a create event pop up on #35 is ready so you could check it.

**Comment by ronanpnc** [comment]
I cannot create an account an login on your branch

**Comment by ronanpnc** [comment]
@vannuthchhorn 
Why you put on REVIEW without any COMMIT ?

**Comment by ronanpnc** [comment]
@vannuthchhorn
Why you put on REVIEW without any COMMIT ?

**Comment by vannuthchhorn** [comment]
@ronanpnc 
Dear teacher, 
now I cannot upload the image when creating an event I try to do it on my best but it always errors

**Comment by ronanpnc** [comment]
We will see this after the meeting, at 3PM
