### ISSUE TITLE
Create account view : if error occured when click on SUBMIT, all field are cleared

### ISSUE THREAD

**Issue by ronanpnc** [pnc-virtual-company/2020-G9-letsgo#38]
Steps to reproduce:
- Click on Create account
- Enter a password, and make a mistake on the confirmation password
- CLick on SUBMIT button

BUG 1 
All field are cleared - It is not good, we would like to keep the field to avoid to edit them again

BUG 2
Label of error is not correct : it should be "Password and confirmation password do not match"

![B1](https://user-images.githubusercontent.com/67727245/88314097-a352cb00-cd3e-11ea-936a-e61fd4ace929.png)

**Comment by daduon** [comment]
@ronanpnc  Good morning teacher. We need the teacher to explain my group again about BUG 1(All field are cleared - It is not good, we would like to keep the field to avoid to edit them again)

**Comment by ronanpnc** [comment]
If you make a mistake when sign in or up,  when error is displayed, all
field are cleared and we need to type them again

you should keep the values on the fields

**Comment by sreyneang040** [comment]
@ronanpnc Good afternoon teacher. I have completed my hot bug (#38 Create account view : if error occurred when click on SUBMIT, all field are cleared). I would like inform you help to review it.
