### ISSUE TITLE
After creating account, will should be already signed in

### ISSUE THREAD

**Issue by ronanpnc** [pnc-virtual-company/2020-G9-letsgo#39]
After creating an account, it would be nice to be already signed in
and avoid to have to sign in again

**Comment by vannuthchhorn** [comment]
@ronanpnc 
I Already completed on (#39 After creating an account, will be already signed in ).
You can review it.
Thanks in advance.

**Comment by vannuthchhorn** [comment]
@ronanpnc 
Teacher, I want to ask you about these bugs I do it already but I want you to feedback about my bugs to implement and make it improve.
Best regards.
vannuth chhorn
