### ISSUE TITLE
The profile popup menu is NOT accessible

### ISSUE THREAD

**Issue by ronanpnc** [pnc-virtual-company/2020-G9-letsgo#42]
See the picture
When clicking on the PROFILE menu, the menu is on the right side and cannot be accessed

![B3](https://user-images.githubusercontent.com/67727245/88320005-2bd56980-cd47-11ea-94fa-ef9c0915a3b8.png)

**Comment by sreyneang040** [comment]
@ronanpnc I would like to inform you help to review about the hot bug (The profile popup menu is NOT accessible #42). I have already completed.
