### ISSUE TITLE
(exlore event view) filters event search

### ISSUE THREAD

**Issue by sreylengchheang** [pnc-virtual-company/2020-G9-letsgo#48]
thing to display 
   + search all even
       - search tittle of event
       - search category 
       - search descation

**Comment by sreylengchheang** [comment]
@ronanpnc 
Hello teacher for search event filter it means search all event (pass and present)???

**Comment by ronanpnc** [comment]
You have many way to organize your code

- you put all the filter in the same function :
 if   (isFutureEvent && machesWithFilter & etc..) {
   // then add this event to the list of event to display
}

- or you can separate into differents small function

List<Event>  getFutureEvent( list )
List<Event>  getEventsOwnByUSer( list)

and then you filter by calling in cascade each function :

eventsTOdsiplay =  getFutureEvent (  getEventsOwnByUSer (
getEventMatchingWithKeywords( allEvnet,  keyword) ) )


it's up to you

Maybe for know the first approach would be easier to do


Ronan OGOR, WEP Coordinator

Passerelles numériques CAMBODIA

BP511 St. 371 Phum Tropeang Chhuk (Borey Sorla), Sangkat Tek Thla, Khan Sen
Sok, Phnom Penh, CAMBODIA

Email@passerellesnumeriques.org | Phone: + 855 23 99 55 00 | Mobile: +855
96 49 02 951 | Skype ID: ronan.ogor

<https://www.passerellesnumeriques.org/en/about-us/our-organisation/>

<http://www.passerellesnumeriques.org/>
<https://www.facebook.com/passerelles.numeriques>
<https://www.linkedin.com/company/455759/>
<https://twitter.com/passerellesNume>
<http://www.youtube.com/user/PasserellesNumerique>

**Comment by sreylengchheang** [comment]
@ronanpnc 
Hello teacher for search event filters like this ???
![filter](https://user-images.githubusercontent.com/53991715/88945823-ac9ce400-d2b8-11ea-8f1c-e4400f759953.PNG)
But it show date time outside the card
