### ISSUE TITLE
Bug of Edit Profile ( city,  date-of-birth, image )

### ISSUE THREAD

**Issue by sreyneang040** [pnc-virtual-company/2020-G9-letsgo#54]

**Comment by ronanpnc** [comment]
If it's a bug it's not an improvement, it' one of them !

**Comment by sreylengchheang** [comment]
@Sethmok 
     Hello Mr.Piseth for field date of birth , city and gender you told me to set requeire and I have followed you. But my Project Manger told me about rulse of update pop up in optional user want update or no update it ok. So do you agree if I take out of 3 field above???? For image I try to do for you but it still error.

**Comment by sreylengchheang** [comment]
@ronanpnc 
Hello teacher for passwork in field edit profile I tryi to follow you but it not work

**Comment by ronanpnc** [comment]
great
