### ISSUE TITLE
Bug On Menu

### ISSUE THREAD

**Issue by sreyneang040** [pnc-virtual-company/2020-G9-letsgo#62]
- When I click on your event, it directs me to your event page, but it still highlights Explore events as if i was still in the Explore event page. 
- Explor event is incorrect spelling. It should be Explore Event.

**Comment by sreyneang040** [comment]
@Sethmok 

Dear teacher,

I would to inform you about the bug. Right now I have fixed bug on the menu and spelling already.

Thank you

**Comment by ronanpnc** [comment]
Thx,  great description for this bug !
