### ISSUE TITLE
Your events view HMTL

### ISSUE THREAD

**Issue by daduon** [pnc-virtual-company/2020-G9-letsgo#7]
A view composed of
- HTML AND CSS

**Comment by sreyneang040** [comment]
@ronanpnc Good morning project manager. Your events view is completed. please teacher help to review my task already completed.

**Comment by ronanpnc** [comment]
UserController should contains only operations related to the user sign-in, sign out, sign up

It hsould not contains actions related to Navigation in the menu  ==> create a NavigationCOntroler for this if needed

**Comment by sreyneang040** [comment]
@ronanpnc  I have already completed again of my task related to your events view. Please teacher help review it
