### ISSUE TITLE
Register view HTML

### ISSUE THREAD

**Issue by daduon** [pnc-virtual-company/2020-G9-letsgo#8]
A view composed of
- Register view with HTML and CSS

**Comment by Puthy-Ouk** [comment]
@Sethmok  
On form register,  you need to add a collum confirm password or not.

**Comment by Sethmok** [comment]
@Puthy-Ouk I would like to confirm some features on form register. First Name, Last Name, Gender, Date of Birth, Password, Confirm Password. (no adding picture).
